# フクログマ（ノーマル・かくとう × オウルベア）手打ち GBA風
META = dict(id='fukuroguma', name='フクログマ', types=['normal', 'fighting'], base='オウルベア', size='L')
PAL = {
    'k': '#101018', 'l': '#3a2216',
    'F': '#dcaa72', 'G': '#9c6a40', 'H': '#5a3824',
    'D': '#f6e8ca', 'E': '#c6a87e',
    'C': '#f4d26c', 'c': '#ac7428',
    'O': '#ff9a1e', 'Y': '#fff27a',
    'R': '#e2483a', 'r': '#8c2430',
    'w': '#ffffff',
}
LIGHT = set('FDCYRw')

HEAD = [
    '.kk..................kk.',
    '.kGk................kGk.',
    '..kGk..............kGHk.',
    '..kGGk............kGHk..',
    '..kFGGkkkkkkkkkkkkGHHk..',
    '.kFFFFFFFFFFFFFFFFFGHk..',
    '.kFFFFFFFFFFFFFFFFFFGk..',
    'kFFFFFFFFFFFFFFFFFFFGHk.',
    'kFFkkkFFFFFFFFFFkkkFGHk.',
    'kFHHHHkkkkFFFkkkHHkkGHk.',
    'kHDDDDHHHHkkkkHHDHHkGHk.',
    'kHDkkkkkkHHDEHHkkkDkHk..',
    'kHDkOOOOYkHDEHkOYkDkHk..',
    'kGHDkOOkOkDkCkkOkkDEHk..',
    'kGHDEkOOkDkCCkkkkDEEHk..',
    'kGHDEEkkDkCCCkDEEEEHk...',
    'kGHGEEEEEkCCcckEEEHk....',
    '.kGHGEEEEkCcckEEEHk.....',
    '.kGHGGEEEEkcckEGHk......',
    '..kGHGGEEEkckGGHk.......',
    '...kGHGGGGkkGGHk........',
    '....kkGHHHHHHHkk........',
    '......kkkkkkkk..........',
]
BODY = [
    '.....kkkkkkkkkkkkk..........',
    '...kkFFFFFFFFFFFFFkkk.......',
    '..kFFFFFFFFFFFFFFFFFFk......',
    '.kFFFFFFFFFFFFFFFFFFFFk.....',
    'kFFFFFFGGGGGGGGGGGGFFFk.....',
    'kFFFFGGGGFGGGGGGGGGGGEEk....',
    'kFFFGGGGGGFGGGGGGGGGEEEk....',
    'kFFGGGFGGGGGGGGGGGGEEDEk....',
    'kFGGGGGFGGGGGGGGGGEEEEEEk...',
    'kFGGGGGGGGGGGGHGGGEEDEEDk...',
    '.kGGGGGGGGGGGGGHGEEEEEEEk...',
    '.kGGGGGGFGGGGGGGGEEDEEDEk...',
    '.kGGGGGGGFGGGGGGGEEEEEEEk...',
    '..kGGGGGGGGGGGGHGDEDEEDEk...',
    '..kGGGGGGGGGGGGGHDEEEEEDk...',
    '..kGGGGGGGGGGGGGHDDEDEEDk...',
    '...kGGGGGGGGGGHGHDDEEEEDk...',
    '...kGGGGGGGGGGGHHDDDEDDk....',
    '...kHGGGGGGGGGGHHDDDDDDk....',
    '...kHGGGGGGGGGHHHHDDDDDk....',
    '...kHHGGGGGGGHHHHHHDDDk.....',
    '...kHHGGGGGGHHHHHHHHHHk.....',
    '...kHHHGGGHHHHHHHHHHHHk.....',
    '....kkHHHHHHHHHHHHHHkk......',
    '......kkkkkkkkkkkkkk........',
]
RUFF = [
    'kDDDDEDDDDEDDDDEDDDk..',
    'kDEDDEDEDDEDEDDEDEEk..',
    '.kDkEDkDEkDDkEDkEEk...',
    '..k.kk.kk.kk.kk.kk....',
]
ARM_F = [
    '....kkkkkkk.............',
    '..kkFFFFFFFkk...........',
    '.kFFFFFFFFFFGk..........',
    'kFFFFFFFFFFGGGk.........',
    'kFFFFFFFFFGGGGHk........',
    'kFFFFFFFGGGGGGHk........',
    'kFFFFFGGGGGGGHHk........',
    '.kFFGGGGGGGGGHHk........',
    '.kFGGGGGGGGGHHHk........',
    '..kGGGGGGGGGHHHk........',
    '..kGGGGGGGGHHHk.........',
    '...kGGGGGGGHHHk.........',
    '...kFGGGGGGHHHHk........',
    '...kFGGGGGGGHHHk........',
    '....kFGGGGGGHHHHk.......',
    '....kRRRRRRRRrrrk.......',
    '....kRrRRRRRRrrrrk......',
    '....kRRRRRRRRrrrrk......',
    '.....kRrRRRRRRrrrk......',
    '.....kRRRRRRRrrrrrk.....',
    '.....kkFFFGGGGGGHHk.....',
    '....kFFFFGGGGGGGHHHk....',
    '....kFFFGGGGGGGGGHHHk...',
    '...kFFGGGGGGGGGGGHHHk...',
    '...kFGGGGkGGGGkGGGHHHk..',
    '...kGGGGGkGGGGkGGGGHHk..',
    '...kGGGGkGGGGkGGGGHHHk..',
    '....kHHkkHHHkkHHHkHHk...',
    '....kwwk.kwwk.kwwk.kwk..',
    '.....kwk..kwk..kwk..kk..',
    '.....kwk..kwk..kwk......',
    '......k....k....k.......',
]
ARM_B = [
    '.k...k...k......',
    'kwk.kwk.kwk.....',
    'kwk.kwk.kwk.k...',
    'kwkkkwkkkwkkwk..',
    'kGHkGHkGHkkwk...',
    'kGGkGGkGGHkHk...',
    'kGGGGGGGGHHHk...',
    '.kGGGGGGGHHHk...',
    '.kRRRRRrrrrk....',
    '.kRrRRRrrrrk....',
    '.kRRRRRrrrrk....',
    '..kGGGGHHHHk....',
    '..kGGGGHHHHk....',
    '...kGGGHHHHHk...',
    '...kGGGHHHHHk...',
    '....kGGGHHHHHk..',
    '....kGGGHHHHHk..',
    '.....kGGGHHHHHk.',
    '.....kGGGHHHHHk.',
    '......kGGHHHHHk.',
    '......kGGHHHHHHk',
    '.......kkkkkkkk.',
]
LEG = [
    '..kkkkkkkk....',
    '.kFFGGGGGHk...',
    'kFFGGGGGGHHk..',
    'kFGGGGGGGHHHk.',
    'kFGGGGGGGHHHk.',
    'kGGGGGGGGHHHk.',
    '.kGGGGGGHHHk..',
    '..kGGGGGHHk...',
    '..kGGGGGHHk...',
    '..kFGGGGHHk...',
    '..kFGGGGHHHk..',
    '.kFGGGGGHHHk..',
    '.kFGGGGGGHHHkk',
    'kFGGGGGGGGHHHk',
    'kGGGGGGGGGHHHk',
    'kwkkwkkwkkwkk.',
    '.k..k..k..k...',
]
DLEG = [r.replace('F', 'G') for r in LEG]

EYEN = ['kkkkkk.', 'kOOOOYk', '.kOOkOk', '..kOOk.']
EYEN_ALT = {
    'blink': ['kkkkkk.', 'kEEEEEk', '.kkkkkk', '..kEEk.'],
    'atk0|atk1|atk2': ['kkkkkk.', 'kYYYYwk', '.kYOkYk', '..kOOk.'],
    'hit': ['kkkkkk.', 'kkkOkkk', '.kOkkOk', '..kkkk.'],
    'ko': ['kkkkkk.', 'kOkEkOk', '.kEOEkk', '..kOkk.'],
}
EYEF = ['.kkk', 'kOYk', 'kOkk']
EYEF_ALT = {'blink': ['.kkk', 'kEEk', 'kkkk'], 'atk0|atk1|atk2': ['.kkk', 'kYwk', 'kOkk'], 'hit|ko': ['.kkk', 'kkOk', 'kOkk']}
# 攻撃：まっすぐの 正拳（腕を 前へ）
PUNCH = [
    '..kkkkkkk.........................',
    '.kFFFFFFGkkkkkkkkkkk....kkkkkkk....',
    'kFFFFFFGGGGGGGGGGGGGkkkkFFFFFFGkk..',
    'kFFFFFGGGGGGGGGGGGGGkRRRkFFFFGGGHk.',
    'kFFFFGGGGGGGGGGGGGGHkRrRkFFGGGGGHk.',
    'kFFFGGGGGGGGGGGGGHHHkRRRkFGGGGGHHHk',
    '.kFGGGGGGGGGGGHHHHHHkRrRkkkkGGkGHHk',
    '.kGGGGGGGGGHHHHHHHHHkRRRkGGGkGGkHHk',
    '..kGGGGGGHHHHHHHHHHHkRrRkkkkGGkGHHk',
    '...kHHHHHHHHHHHHHHHHkRRRkGGGkGkHHHk',
    '....kkkkkkkkkkkkkkkkkkkkkHHHHHHHHk.',
    '........................kkkkkkkkk..',
]
IMPACT = [
    '.....k......',
    '....kYk...k.',
    'k...kYk..kYk',
    'kYk.kwYk.kYk',
    '.kYkkwwYkYk.',
    '..kYwwwwwYk.',
    'kkYwwwwwwYkk',
    '..kYwwwwYk..',
    '.kYkYwwkYYk.',
    'kYk.kwYk.kYk',
    'k...kYk...k.',
    '....kYk.....',
    '.....k......',
]
RAKE = [
    'kk......kk......kk......',
    'kwk.....kwk.....kwk.....',
    '.kwk.....kwk.....kwk....',
    '..kwk.....kwk.....kwk...',
    '...kwk.....kwk.....kwk..',
    '....kYk.....kYk.....kYk.',
    '.....kYk.....kYk.....kYk',
    '......kk......kk......kk',
]

def layers():
    return [
        dict(n='armB', g='armB', x=6, y=4, rows=ARM_B, not_='ko'),
        dict(n='legB', g='legB', x=18, y=44, rows=DLEG),
        dict(n='body', g='body', x=15, y=19, rows=BODY),
        dict(n='legA', g='legA', x=30, y=44, rows=LEG),
        dict(n='head', g='head', x=31, y=3, rows=HEAD),
        dict(n='eyeN', g='head', x=34, y=14, rows=EYEN, alt=EYEN_ALT),
        dict(n='eyeF', g='head', x=45, y=14, rows=EYEF, alt=EYEF_ALT),
        dict(n='ruff', g='head', x=31, y=23, rows=RUFF),
        dict(n='armF', g='armF', x=36, y=22, rows=ARM_F, not_='atk1'),
        dict(n='punch', g='armF', x=36, y=22, rows=PUNCH, only='atk1'),
        dict(n='impact', g='fx', x=66, y=20, rows=IMPACT, only='atk1'),
        dict(n='rake', g='fx', x=55, y=28, rows=RAKE, only='atk2'),
    ]

FRAMES = {
    'idle0': {},
    'idle1': {'body': (0, 1), 'armB': (0, 0)},
    'idle2': {'body': (0, 1), 'head': (0, 1), 'armB': (0, -1)},
    'idle3': {'body': (0, 0), 'armB': (0, -1)},
    'blink': {},
    'walk0': {'legA': (2, -1), 'legB': (-1, 0), 'armF': (1, 0)},
    'walk1': {'body': (0, -1)},
    'walk2': {'legA': (-1, 0), 'legB': (2, -1), 'armF': (-1, 0)},
    'walk3': {'body': (0, -1)},
    'atk0': {'body': (-2, 1), 'head': (-1, 1), 'armF': (-4, -2), 'armB': (1, 2)},
    'atk1': {'root': (5, 0), 'body': (1, 0), 'legA': (2, 0)},
    'atk2': {'root': (7, 1), 'armF': (3, -2), 'armB': (3, 3)},
    'hit': {'root': (-3, 0), 'body': (-1, 0), 'head': (-2, -1), 'armF': (-2, 1), 'armB': (-2, 2)},
    'ko': {'body': (0, 9), 'head': (3, 5), 'armF': (1, -1), 'legA': (3, 1), 'legB': (-2, 1)},
}
PARENT = {'fx': 'root', 'head': 'body', 'armF': 'body', 'armB': 'body', 'body': 'root', 'legA': 'root', 'legB': 'root'}
