# スナミミズ（じめん × 巨大ミミズ）手打ち GBA風
META = dict(id='sunamimizu', name='スナミミズ', types=['ground'], base='巨大ミミズ', size='L')
EYE_BOX = (39, 8, 6, 18)   # 多眼 5つ（idle0）
PAL = {
    'k': '#101018', 'l': '#3c2418',
    'U': '#f2d496', 'V': '#c8984c', 'X': '#875a2c',
    'P': '#eaa292', 'Q': '#b86262', 'R': '#783442',
    'r': '#3e0e1c', 'w': '#fff6dc', 'n': '#c8b490',
    'S': '#ecd08a', 's': '#b48c4a',
    'Y': '#ffd040', 'O': '#d86410',
}
LIGHT = set('UPwS')
KEEP_BLACK = set('wnrYO')

# 体：砂岩の よろいの 節。腹がわは 赤い 肉
BODY = [
    '...............................kkkkkkkkkk....',
    '...........................kkkkXUUUUUXXXXk...',
    '.........................kkUUUUXUUUUUXXXXXk..',
    '.......................kkUUUUUUXUUUUVXXXXXXk.',
    '.....................kkXUUUUVVVXUVVVVXXXXXXXk',
    '....................kUUXXUUVVVVXUVVVVXXXXXXXk',
    '..................kkUUUUXUVVVVVXUVVVVXXXXXXXk',
    '.................kUUUUUVVXVVVVVVXVXXXXXXXXXXk',
    '................kUUUUUVVVXUVVXXXXXXXXXRRRRRRk',
    '...............kXUUUUVVVVVXVXXXXRQQQQQRRRRRRk',
    '..............kUUXXUUVVVVVXXXXQQRPQQQQRRRRRk.',
    '.............kUUUUXXUUVVXXXRPQQQRPQQQQRRRRk..',
    '.............kUUUVVVXUVXXXXQRQQQRRRRRRRRRk...',
    '............kUUUVVVVVXXXXQQQRRRRRRRRkkkkk....',
    '...........kUXUUVVVVVXXPQQQQQRRRkkkk.........',
    '..........kUUUXUVVVVXXXQQQQRRRkk.............',
    '.........kUUUUVXXUVXXXQQQQRRRk...............',
    '.........kUUUVVVXXUXXQQQQRRkk................',
    '........kUUUVVVVVXXXXQQQRRk..................',
    '........kUUUVVVVVXXRRPQQRRk..................',
    '.......kXXUUVVVVXXXQRRPRRk...................',
    '.......kUXXXUUVVXXQQQQRRk....................',
    '......kUUUUXXXUXXXQQQQRRk....................',
    '......kUUUVVVVXXXPPQQRRk.....................',
    '......kUUUVVVVVXRRRPRRk......................',
    '.....kXUUVVVVVXXXQQRRRk......................',
    '.....kXXXUVVVVXXQQQQRRk......................',
    '....kUUUUXXUVXXXQQQRRk.......................',
    '....kUUUVVVXXXXQQQQRRk.......................',
    '....kUUUVVVVVXRRPPQRRk.......................',
    '...kUUUVVVVVXXXQRRRRk........................',
    '...kUUUVVVVVXXQQQQRRk........................',
    '...kXUUVVVVVXXQQQQRRk........................',
    '...kXXXXUUUXXXQQQRRk.........................',
    '..kUUUUVXXXXXXPPPRRk.........................',
    '..kUUUVVVVVXXRRRRRRk.........................',
    '..kUUUVVVVVXXQQQQRRk.........................',
    '..kUUUVVVVVXXQQQQRRk.........................',
    '.kXUUUVVVVXXXQQQQRk..........................',
    '.kXXXXXUUUXXXQQQRRk..........................',
    '.kXXXXXXXXXXXPPPRRk..........................',
    '.kUUUVVVVVXXQQRRRRk..........................',
    '.kUUUVVVVVXXQQQQRRk..........................',
    '.kUUUVVVVVXXQQQQRRk..........................',
    '.kUUUVVVVVXXQQQQRRk..........................',
    '.kUUUUUUUUXXQQQQRRk..........................',
    '.kXXXXXXXXXRRRPPRRk..........................',
    'kUUUUVVVVXXXQQRRRk...........................',
    'kUUUUVVVVXXXQQQRRk...........................',
    'kUUUVVVVVXXXQQQRRk...........................',
    'kUUUVVVVVXXXQQQRRk...........................',
    'kXUUUUUUUXXXQQQRRk...........................',
    'kXXXXXXXXXXRRRPRRk...........................',
    'kXXXXXXXXXXRRRRRRk...........................',
    'kXXXXXXXXXRRRRRRRk...........................',
    'kXXXXXXXXXRRRRRRRk...........................',
    '.kXXXXXXXXRRRRRRk............................',
    '..kkkkkkkkkkkkkk.............................',
]
# 頭：まるい 口に 何重もの 牙（右前 3/4 から）
MAW = [
    '.......kkkkkkkk.......',
    '.....kkUUUUUUUVkk.....',
    '....kUUUUUPPPPPPVk....',
    '...kUUUUUPPPPPPPQQk...',
    '..kUUUUUPPPPnnPPQQQk..',
    '..kUUUUPPPnnrnnnQQQk..',
    '.kUUUUPPPnnrrnnrrQQQk.',
    '.kUUUUPPrrnrrrrrrnQQk.',
    'kUUUUUPPrrrrrnrrnnwQQk',
    'kUUUUPPnnrrnrnrrnrwQQk',
    'kUUUUPPnnrnnrkrwrrrQQk',
    'kUUUUPPnnrrrkkkwwrrwQk',
    'kUUUUPPrrrnkkkkrrrwwQk',
    'kUUUVPPrrrnkkkkrrrwwQk',
    'kUUVVQQnnrrrkkkwwrrwQk',
    'kUVVVQQnnrnwrkrwrrrQQk',
    'kVVVVQQnnrrwrwrrwrwQQk',
    'kVVVVVQQrrrrrwrrwwwQQk',
    '.kVVVVQQrrwrrrrrrwQQk.',
    '.kVVVVQQQnwrrwwrrQQQk.',
    '..kVVVVQQQwwrwwwQQQk..',
    '..kVVVVVQQQQwwQQQQQk..',
    '...kVVVVXQQQQQQQQQk...',
    '....kVVXXXQQQQQQXk....',
    '.....kkXXXXXXXXkk.....',
    '.......kkkkkkkk.......',
]
MAW_OPEN = [
    '........kkkkkkkk........',
    '......kkUUUPPPPPkk......',
    '.....kUUUPPPPPPPPPk.....',
    '....kUUUPPPPPPPPPPQk....',
    '...kUUUPPPPPnnnrnPQQk...',
    '..kUUUUPPPnrnnrrnnnQQk..',
    '.kUUUUPPPnnrrnrrnnrrQQk.',
    '.kUUUUPPnnnrrnrrnrrrQQk.',
    'kUUUUPPPrnnrrrrrrrrnwQQk',
    'kUUUUPPnrrrnnnrnnrrwwQQk',
    'kUUUUPPnnrrrrnrnrrnwwwQk',
    'kUUUPPPnnrrrrkkkrwrrrrQk',
    'kUUUPPPnnrnnkkkkrwwrrwQk',
    'kUUUPPPrrrrrkkkkkrrrwwQk',
    'kUUUPPPrrrrrkkkkkrrrwwQk',
    'kUUVQQQnnrnnkkkkrwwrrwQk',
    'kUVVQQQnnrrrrkkkrwrrrrQk',
    'kUVVVQQnnrrrrwrwrrwwwwQk',
    'kVVVVQQnrrrnwwrwwrrwwQQk',
    'kVVVVQQQrnnrrrrrrrrwwQQk',
    '.kVVVVQQnnnrrwrrwrrrQQk.',
    '.kVVVVQQQnwrrwrrwwrrQQk.',
    '..kVVVVQQQwrwwrrwwwQQk..',
    '...kVVVQQQQQwwwrwQQQk...',
    '....kVVVQQQQQQQQQQQk....',
    '.....kVVXQQQQQQQQQk.....',
    '......kkXXXQQQQQkk......',
    '........kkkkkkkk........',
]
# ダウン：砂の 上に たおれる 体
BODY_KO = [
    '.......................kkkkkkkk...........',
    '..................kkkkkUUUUUUUXkkk........',
    '...............kkkUUUXUUUUUUUUXUUUkkk.....',
    '..............kUUUUUUXUUUUVVVXUUUUUUXkk...',
    '.............kUUUUUUUVUVVVVVVXVVVUUXUUUk..',
    '............kXUUVVVVVVXVVVVVVXVVVVVXUUUUk.',
    '...........kUXUUVVVVVVXUVVVVXUVVVVVXUUUUk.',
    '..........kUUUXUVVVVVVXUVVXXXXVVVVXUUUUUUk',
    '.........kUUUUVXUVVVVXXXXXXXRXXXXVXUUUUUUk',
    '........kUUUUVVVXUXXXXXXXXQQPQXXXXXXXUUUUk',
    '.......kXXUUVVVVVXXXXQQRQQQQPQQQQRXXXXXXUk',
    '......kUUXXUVVVVXXRPQQQRPQQQPQQQQRPPPXXXk.',
    '.....kUUUUXXUVVXXXQRPQQRPRRRRRQQQRPPPPPPk.',
    '....kUUUUVVXXUXXXQQQRPRRRRRRRRRRRRPPPPPk..',
    '....kUUUVVVVXXXXQQQQQRRRkkkkkkkkRRRRRkk...',
    '....kUUUVVVVXXRPQQQQRRkk........kkkkk.....',
    '...kUUUVVVVVXXRRPQQRRk....................',
    '...kXUUVVVVXXXQRRPRRk.....................',
    '..kUUXXXUUVXXQQQRRRk......................',
    '..kUUUVVXXUXXQQQRRk.......................',
    '..kUUUVVVVXXRPPQRRk.......................',
    '.kUUUVVVVVXXQRRRRk........................',
    '.kUUUVVVVXXXQQQRRk........................',
    'kXXXUUVVVXXQQQQRRk........................',
    'kXXXXXXUUXXQQQRRk.........................',
    'kXXXXXXXXXPQQQRRk.........................',
    'kXXXXXXXXRRRPRRk..........................',
    'kXXXXXXXXRRRRRRk..........................',
    '.kkkkkkkkkkkkkk...........................',
]
BODY_KO = BODY_KO[:15]
BODY = BODY[:50]   # 下は 砂に うまる
def rows_cut(rows, y0, y1): return ['.' * len(rows[0])] * y0 + rows[y0:y1]
# 砂山：体が 出てくる 穴の まわり
SAND = [
    '...................kkkkkkkkkkkkkkkkk........................',
    '.............kkkkkkSSSSSSSSSSSSSSSSSkkkkk...................',
    '..........kkkSSSSSSSSSSSSSSSSSSSSSSSSSSSSkkkk...............',
    '.......kkkSSSSSSSSSSSSSsSSSSSSSSSSSSSSSSSSSSSSkkkk..........',
    '.....kkSSSSSSSSSSSSSSSsSSSSSSSSSSSSSSsSSSSSSSSSSSSSkkk.......',
    '...kkSSSSSssSSSSSSSSSSSSSSSSSSSSSSSsSSSSSSSSSSssSSSSSSkk.....',
    '..kSSSSSSSSSSSSSSSSsssSSSSSSSSSSSSSSSSSSSSSSSSSSSSSssSSSkk...',
    '.kSsSSSSSSSSSSSSSSSSSSSSssSSSSSSSSSSSSSSSSsssSSSSSSSSSSSSSk..',
    'kssssSSSSSSSSSssssSSSSSSSSSSSssssSSSSSSSSSSSSSSssssssssssssk.',
    'ksssssssssssssssssssssssssssssssssssssssssssssssssssssssssssk',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
]
# こぼれ落ちる 砂
FALL = [['S.....', '......', '.s..S.', '......', 's.....', '...s..'], ['......', 'S...s.', '......', '.S....', '......', 's..S..']]
# 目：多眼（N）。口の ふちの よろいに 砂色の だいだいの 目が 5つ、大きさを 変えて ならぶ（大 1・中 2・小 2）。
#   どれも まぶたの ない つやの ある 玉：白い 光（w）＋ 黄（Y 明）＋ だいだい（O 中）＋ こげ茶（X 暗）、黒い ふち。たての ひとみは なし
EYES = {
    'L': {'idle': ['.kkk.', 'kwYOk', 'kYOOk', 'kOOXk', '.kkk.'], 'blink': ['.kkk.', 'kVVVk', 'kkkkk', 'kOOXk', '.kkk.'],
          'atk': ['.kkk.', 'kwwYk', 'kwYYk', 'kYYOk', '.kkk.'], 'hit': ['.kkk.', 'kOkOk', 'kkOkk', 'kOkXk', '.kkk.'],
          'ko': ['.kkk.', 'kVkVk', 'kkVkk', 'kVkVk', '.kkk.']},
    'M': {'idle': ['.kk.', 'kwOk', 'kOXk', '.kk.'], 'blink': ['.kk.', 'kVVk', 'kkkk', '.kk.'],
          'atk': ['.kk.', 'kwYk', 'kYOk', '.kk.'], 'hit': ['.kk.', 'kOkk', 'kkXk', '.kk.'], 'ko': ['.kk.', 'kkVk', 'kVkk', '.kk.']},
    'S': {'idle': ['.k.', 'kYk', '.k.'], 'blink': ['...', 'kkk', '...'], 'atk': ['.k.', 'kwk', '.k.'],
          'hit': ['.k.', 'kXk', '.k.'], 'ko': ['...', '.k.', '...']},
}
def eye(sz):
    e = EYES[sz]
    return dict(rows=e['idle'], alt={'blink': e['blink'], 'atk0|atk1|atk2': e['atk'], 'hit': e['hit'], 'ko': e['ko']})
# 口の まわりの 岩の とげ
SPK_U = ['kk...', 'kUkk.', '.kUVk', '..kk.']
SPK_L = ['kkk..', 'kUVkk', '.kkVk']
# 攻撃：砂の 爆発
BURST = [
    '..s....S..',
    'S...S.....',
    '..SsS..s..',
    '.sSSSs....',
    'SSSsSSS.s.',
]
def layers():
    return [
        dict(n='bko', g='root', x=4, y=41, rows=BODY_KO, only='ko'),
        dict(n='b0', g='b0', x=8, y=10, rows=rows_cut(BODY, 30, 50), not_='ko'),
        dict(n='b1', g='b1', x=8, y=10, rows=rows_cut(BODY, 14, 33), not_='ko'),
        dict(n='b2', g='b2', x=8, y=10, rows=rows_cut(BODY, 0, 17), not_='ko'),
        dict(n='fall', g='b1', x=33, y=30, rows=FALL[0], alt={'idle1|idle3|walk1|walk3': FALL[1]}, not_='atk0|atk1|atk2|hit|ko'),
        dict(n='spk1', g='head', x=41, y=5, rows=SPK_U),
        dict(n='spk2', g='head', x=36, y=12, rows=SPK_L),
        dict(n='maw', g='head', x=38, y=7, rows=MAW, alt={'atk1|atk2': MAW_OPEN}),
        dict(n='e1', g='head', x=42, y=8, **eye('S')),
        dict(n='e2', g='head', x=40, y=10, **eye('M')),
        dict(n='e3', g='head', x=39, y=14, **eye('L')),
        dict(n='e4', g='head', x=40, y=19, **eye('M')),
        dict(n='e5', g='head', x=40, y=23, **eye('S')),
        dict(n='sand', g='root', x=2, y=50, rows=SAND),
        dict(n='burst', g='root', x=6, y=45, rows=BURST, only='atk1'),
    ]
FRAMES = {
    'idle0': {}, 'idle1': {'b2': (0, -1)}, 'idle2': {'b1': (0, -1), 'b2': (0, -1)}, 'idle3': {'b2': (0, -1), 'b1': (0, 0)},
    'blink': {},
    'walk0': {'b1': (-1, 0), 'b2': (-1, 0)}, 'walk1': {'b2': (0, -1)}, 'walk2': {'b1': (1, 0), 'b2': (1, 1)}, 'walk3': {'b2': (0, -1)},
    'atk0': {'b1': (-1, -1), 'b2': (-2, -2), 'head': (-1, -1)}, 'atk1': {'b1': (1, 0), 'b2': (3, 1), 'head': (2, 2)}, 'atk2': {'b1': (1, 0), 'b2': (2, 1), 'head': (1, 1)},
    'hit': {'b1': (-1, 0), 'b2': (-2, 1), 'head': (-1, 1)}, 'ko': {'head': (3, 28)},
}
PARENT = {'head': 'b2', 'b2': 'b1', 'b1': 'b0', 'b0': 'root'}
