# トカゲムシャ（ドラゴン・かくとう × リザードマン）手打ち GBA風
META = dict(id='tokagemusha', name='トカゲムシャ', types=['dragon', 'fighting'], base='リザードマン', size='M')
PAL = {
    'k': '#101018', 'l': '#1e3a2c',
    'G': '#9ed67c', 'H': '#4f9a58', 'J': '#2a5e44',
    'B': '#f2e2a6', 'b': '#bc9a5c',
    'A': '#f2b452', 'a': '#a8682c', 'z': '#5a321e',
    'S': '#e2eaf4', 's': '#8a98b6',
    'Y': '#ffe23a', 'R': '#e04040', 'r': '#86203a',
    'w': '#ffffff',
}
LIGHT = set('GBASYRw')

HEAD = [
    '......kkkk..............',
    '....kkGGGGkk............',
    '...kGGGGGGGGkkkk........',
    '..kGGGGGGGGGGGGGkkkk....',
    '..kGGkkkkkkGGGGGGGGGkkk.',
    '.kGGHkYYYkkkkGGGGGGHHHHk',
    '.kGHHkYkYYkHHHHHHHHHkHHk',
    '.kHHHHkkkkHHHHHHHHHHHHJk',
    'kHHHHHHHHHHHHHJJJJJJJJk.',
    'kHHJJkkkkkkkkkkkkkkkkk..',
    'kHJJkwkkwkkkwkkwkkwkwk..',
    'kJJJkkkkkkkkkkkkkkkkkk..',
    'kJJkBkwkkkwkkwkkwkk.....',
    '.kJkBBBBbbbbbbbbbk......',
    '..kkkkkkkkkkkkkkk.......',
]
HORN = [
    'kkk..........',
    'kBBkk........',
    '.kbBBBkk.....',
    '..kbbBBBBkk..',
    '...kkbbbBBBk.',
    '.....kkkbbbk.',
    '........kkk..',
]
FIN = [  # 首の うしろの 赤い ひれ
    '...k......',
    '..kRk.k...',
    '..kRkkRk..',
    '.kRrkRrk..',
    '.kRrkRrkk.',
    'kRrkRrkRk.',
    'kRrkRrkrk.',
    'kkkkkkkkk.',
]
TORSO = [
    '..............kkkk......',
    '.............kGGGHk.....',
    '............kGGGHHk.....',
    '...........kGGGHHBk.....',
    '..........kGGGHHBBk.....',
    '.......kkkGGGHHHBbk.....',
    '.....kkGGGGGAHHHBBbk....',
    '....kGGGGGGAaHHHkBbbk...',
    '...kGGGGGHAaHHHHHBBbk...',
    '..kGGGHHHAaHHHHHkkkkk...',
    '..kGGHHHAaHHHHHHkBBbk...',
    '.kGGHHHAaHHHHHHJkkkkk...',
    '.kGHHHAaHHHHHHJJkBBbk...',
    '.kGHHAaHHHHHJJJkkkkk....',
    '.kHHAaHHHHHJJJJkBbbk....',
    'kHHAaHHHHJJJJJJkkkk.....',
    'kkkkkkkkkkkkkkkkkkk.....',
    'kAAAARRRRAAaaaaaazk.....',
    'kaaaRRrrRaaazzzzzk......',
    '.kkkRrrRkkkkkkkkk.......',
    '....kRrrk...............',
    '....kRrk................',
    '.....kk.................',
]
TAIL = [
    '..................kk..',
    '..............k..kRk..',
    '.........k...kRkkRrkk.',
    '.....k..kRk.kRrkkkGGGk',
    '....kRkkRrkkkkkGGGHHHk',
    '...kRrkkkkkGGGGHHJHHJk',
    '...kkkkGGGGHHHHHHHHJk.',
    '...kkGGHHJHHHHJHJJJk..',
    '..kGGHHHHHHJHJJJJkk...',
    '.kGHHJHHJJJJJkkk......',
    '.kGHHHJJJkkk..........',
    'kGHJJkkk..............',
    'kHJkk.................',
    'kkk...................',
]
LEG = [
    '..kkkkkkk.....',
    '.kGGGGGHHk....',
    'kGGHHHHHHJk...',
    'kGHHHHHHHJk...',
    'kGHHHHHHJJk...',
    '.kHHHHHHJk....',
    '..kHHHHJJk....',
    '...kkHHJJk....',
    '....kHHJk.....',
    '....kGHJk.....',
    '...kGHHJk.....',
    '...kGHJJk.....',
    '..kGHHJk......',
    '..kGHHJJkk....',
    '..kGHHHHJJk...',
    '.kGGHHHHHJJkk.',
    'kwkGHkwkHJkwk.',
    'kwkkkkwkkkkwwk',
    '.k....k....kk.',
]
DLEG = [r.replace('G', 'H').replace('H', 'J', 0) for r in LEG]
SCIM = [
    'kkk.....................',
    'kSSkkk..................',
    '.kwSSSkkk...............',
    '..kwwSSSSkkk............',
    '...kkwwSSSSsskk.........',
    '.....kkwwwSSSsskk.......',
    '.......kkkwwSSSssk......',
    '..........kkwwSSsk......',
    '............kkwSSkk.....',
    '..............kkkkAk....',
    '...............kAAaAk...',
    '................kRk.....',
    '................kRk.....',
    '................kk......',
]
ARM_B = [
    '.kkkk.....',
    'kHHJJk....',
    'kHJJJk....',
    '.kkHJJk...',
    '...kHJJk..',
    '...kHJJk..',
    '....kHJJk.',
    '....kHJJk.',
    '.....kHJk.',
    '.....kkk..',
]
ARM_F = [
    '.kkkkkkk...........',
    'kAAAAAaak..........',
    'kAAaaaaazk.....kk..',
    'kaaazzzzzk...kkGwk.',
    '.kkGHHHHJk..kGGHHwk',
    '...kGHHHJJk.kAAaazk',
    '....kGHHHJk.kAaazkw',
    '....kGHHHJJkAaazkk.',
    '.....kGHHHJAaazk...',
    '.....kGHHJJAazk....',
    '......kHHJJJzk.....',
    '.......kkkkkk......',
]

DORSAL = [
    '..........k...',
    '.........kRk..',
    '.........kRrk.',
    '......k..kRrk.',
    '.....kRk.kkkk.',
    '.....kRrkk....',
    '..k..kRrrk....',
    '.kRk.kkkk.....',
    '.kRrkk........',
    'kRrrk.........',
    'kkkkk.........',
]
EYE = ['YYYk', 'YkYY']
EYE_ALT = {'blink': ['GGGk', 'kkkk'], 'atk0|atk1|atk2': ['wYYk', 'YkYw'], 'hit': ['kYkk', 'YkYk'], 'ko': ['YkYk', 'kYkk']}
# 攻撃：曲刀を 前へ ふりぬく
SCIM_F = [
    '.kkkk.....................',
    'kHHJJk....................',
    'kHJJJkk.kk................',
    '.kHJJkAkSSkkkkkkkk........',
    '..kHkkAkwwSSSSSSSSkkkk....',
    '...kRkaksswwwwSSSSSSSSkk..',
    '...kRk.kkkkksssssSSSSSSSk.',
    '....k......kkkkkkksssSSSk.',
    '..................kkkkkk..',
]
SCIM_D = [
    '.kkkk...........',
    'kHHJJk..........',
    'kHJJJkk.........',
    '.kkJJkAk........',
    '...kkkAak.......',
    '....kRkkSkk.....',
    '....kRk.kwSkk...',
    '.....k...kwSSk..',
    '..........kwSsk.',
    '...........kwSsk',
    '............kwsk',
    '.............kSk',
    '..............kk',
]
ARC = [  # 竜の 気を まとった 横なぎの 斬撃（金）
    '......kkkkkkk.........',
    '...kkkYYYYYYYkkk......',
    '.kkYYwwwwwwwwYYYkk....',
    'kAAwwkkkkkkkkwwwYYkk..',
    'kakkk........kkkwwYYk.',
    '.k..............kkwYAk',
    '..................kwAk',
    '..................kwAk',
    '.................kwAak',
    '...............kkYAak.',
    '.............kkYAakk..',
    '...........kkAAakk....',
    '............kkkk......',
]
KO_BODY = [
    '...k.....k....k.....k.........',
    '..kRk...kRk..kRk...kRk........',
    '..kRrkkkkRrkkkRrkkkkRrkkkk....',
    '...kkkGGGGGGGGGGGGGGGGGGGGkk..',
    '...kGGGGHHHHHHHHHHHHHHHHHHGGk.',
    '..kGGHHHHHHHHJHHHHHJHHHHHHHGk.',
    '..kGHHHJHHHHHHHHHHHHHHHHJHHHk.',
    '.kGHHHHHHHHHHHHHHHHHHHHHHHHJk.',
    '.kHHAAARRRRAAaaaaaHHHHHHHJJJk.',
    '.kHHaaaRrrRaaazzzzHHJJJJJJJk..',
    'kHHHHHJJJJJJJJJJJJJJJJJJJJk...',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkk...',
]
KO_LEG = ['..kkkk..', '.kGHHJk.', 'kGHHJJk.', 'kHHJJk..', 'kkkkkk..']
KO_SCIM = [
    '.kkkkkkkkkkkkkkk....',
    'kwwwwwSSSSSSSSSSkkk.',
    '.kkssssssSSSSSSSSSkAk',
    '...kkkkkkkkkkkkkkkkRRk',
]

def layers():
    N = 'atk1|atk2|ko'
    return [
        dict(n='scim', g='armB', x=8, y=6, rows=SCIM, not_=N),
        dict(n='armB', g='armB', x=23, y=17, rows=ARM_B, not_=N),
        dict(n='dorsal', g='body', x=19, y=19, rows=DORSAL, not_='ko'),
        dict(n='tail', g='tail', x=2, y=36, rows=TAIL, not_='ko'),
        dict(n='legB', g='legB', x=20, y=42, rows=DLEG, not_='ko'),
        dict(n='torso', g='body', x=20, y=22, rows=TORSO, not_='ko'),
        dict(n='legA', g='legA', x=31, y=42, rows=LEG, not_='ko'),
        dict(n='fin', g='head', x=31, y=10, rows=FIN, not_='ko'),
        dict(n='horn', g='head', x=27, y=6, rows=HORN, not_='ko'),
        dict(n='head', g='head', x=34, y=12, rows=HEAD, not_='ko'),
        dict(n='eye', g='head', x=40, y=17, rows=EYE, alt=EYE_ALT, not_='ko'),
        dict(n='armF', g='armF', x=35, y=26, rows=ARM_F, not_='ko'),
        dict(n='scimF', g='armF', x=38, y=28, rows=SCIM_F, only='atk1'),
        dict(n='scimD', g='armF', x=40, y=29, rows=SCIM_D, only='atk2'),
        dict(n='arc', g='fx', x=54, y=25, rows=ARC, only='atk1'),
        # ダウン（うつぶせに たおれる）
        dict(n='koTail', g='ko', x=0, y=44, rows=TAIL, only='ko'),
        dict(n='koLeg', g='ko', x=20, y=55, rows=KO_LEG, only='ko'),
        dict(n='koBody', g='ko', x=14, y=48, rows=KO_BODY, only='ko'),
        dict(n='koScim', g='ko', x=2, y=56, rows=KO_SCIM, only='ko'),
        dict(n='koHorn', g='ko', x=33, y=42, rows=HORN, only='ko'),
        dict(n='koHead', g='ko', x=38, y=46, rows=HEAD, only='ko'),
        dict(n='koEye', g='ko', x=44, y=51, rows=EYE, alt=EYE_ALT, only='ko'),
    ]

FRAMES = {
    'idle0': {},
    'idle1': {'body': (0, 1), 'armF': (0, 0)},
    'idle2': {'body': (0, 1), 'head': (0, 1), 'tail': (0, -1)},
    'idle3': {'body': (0, 0), 'tail': (0, -1)},
    'blink': {},
    'walk0': {'legA': (2, -1), 'legB': (-1, 0), 'tail': (0, 1)},
    'walk1': {'body': (0, -1)},
    'walk2': {'legA': (-1, 0), 'legB': (2, -1), 'tail': (0, 1)},
    'walk3': {'body': (0, -1)},
    'atk0': {'body': (-2, 2), 'head': (-1, 1), 'armB': (-2, -1), 'armF': (-1, 0), 'tail': (1, 0)},
    'atk1': {'root': (5, 0), 'body': (1, 1), 'legA': (2, 0), 'tail': (0, -1)},
    'atk2': {'root': (7, 0), 'body': (1, 2), 'legA': (2, 0)},
    'hit': {'root': (-3, 0), 'body': (-1, 0), 'head': (-2, -1), 'armF': (-2, 1), 'tail': (0, 1)},
    'ko': {},
}
PARENT = {'fx': 'root', 'ko': 'root', 'head': 'body', 'armF': 'body', 'armB': 'body', 'tail': 'body', 'body': 'root', 'legA': 'root', 'legB': 'root'}
